INCLUDEFLAGS=-I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -I..

all: project

project:
	gcc $(INCLUDEFLAGS) lineTest.c -o lineTestApp -lshapes
	#gcc -I/opt/vc/include helloWorld.c -o helloWorldApp -lshapes